// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwlRoorAbqIfuvl6kSYA7hLCk4QeMVp_8',
    appId: '1:398784461305:web:3380b46a9e89166b282528',
    messagingSenderId: '398784461305',
    projectId: 'winable-16c54',
    authDomain: 'winable-16c54.firebaseapp.com',
    storageBucket: 'winable-16c54.appspot.com',
    measurementId: 'G-C9X4Y3GJFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsyhDG5NQyxDawig6llDeXX1cVYa6cHkk',
    appId: '1:398784461305:android:8d4398ef23a83578282528',
    messagingSenderId: '398784461305',
    projectId: 'winable-16c54',
    storageBucket: 'winable-16c54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFiGva8S13JNbF72dnCwuYGdv_Vre7h2w',
    appId: '1:398784461305:ios:f9263b4c047d4c9f282528',
    messagingSenderId: '398784461305',
    projectId: 'winable-16c54',
    storageBucket: 'winable-16c54.appspot.com',
    androidClientId: '398784461305-qcqvv94ciq6a3ghjutcq9u5fhb57jvr4.apps.googleusercontent.com',
    iosClientId: '398784461305-b8imtqhq18gu0ormtevj7ggpifkhh0lo.apps.googleusercontent.com',
    iosBundleId: 'com.winable.winable',
  );
}
